import { serve } from "https://deno.land/std@0.208.0/http/server.ts"
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.50.0'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

interface WelcomeRequest {
  projectId: string;
  projectName: string;
  clientPhone: string;
  clientName?: string;
  clientEmail?: string;
}

/**
 * Format phone number to E.164 format (+1XXXXXXXXXX)
 */
function formatPhoneToE164(phone: string): string {
  if (!phone) return '';
  
  // Remove all non-numeric characters
  const digits = phone.replace(/\D/g, '');
  
  // Handle US numbers
  if (digits.length === 10) {
    return `+1${digits}`;
  }
  
  if (digits.length === 11 && digits.startsWith('1')) {
    return `+${digits}`;
  }
  
  // If already has + prefix, return as-is
  if (phone.startsWith('+')) {
    return phone;
  }
  
  return phone;
}

/**
 * Validate if a phone number is valid
 */
function isValidPhone(phone: string): boolean {
  if (!phone) return false;
  
  const digits = phone.replace(/\D/g, '');
  
  // Valid US numbers are 10 digits or 11 digits starting with 1
  return digits.length === 10 || (digits.length === 11 && digits.startsWith('1'));
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  try {
    const body: WelcomeRequest = await req.json()
    const { projectId, projectName, clientPhone, clientName, clientEmail } = body

    console.log('📬 Send Client Portal Welcome request:', { projectId, projectName, clientPhone: clientPhone?.slice(0, 5) + '***' })

    // Validate required fields
    if (!projectId || !projectName) {
      console.error('❌ Missing required fields: projectId or projectName')
      return new Response(
        JSON.stringify({ error: 'Missing required fields: projectId and projectName' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 400 }
      )
    }

    if (!clientPhone || !isValidPhone(clientPhone)) {
      console.error('❌ Invalid or missing phone number:', clientPhone)
      return new Response(
        JSON.stringify({ error: 'Invalid or missing phone number' }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 400 }
      )
    }

    // Initialize Supabase client with service role
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
    
    const supabase = createClient(supabaseUrl, supabaseServiceKey, {
      auth: {
        autoRefreshToken: false,
        persistSession: false
      }
    })

    // Step 1: Check if client_portal_access record already exists
    const { data: existingAccess, error: accessCheckError } = await supabase
      .from('client_portal_access')
      .select('id, url_slug')
      .eq('project_id', projectId)
      .maybeSingle()

    if (accessCheckError) {
      console.error('❌ Error checking existing portal access:', accessCheckError)
      throw accessCheckError
    }

    let urlSlug: string

    if (existingAccess) {
      console.log('📋 Using existing portal access record:', existingAccess.url_slug)
      urlSlug = existingAccess.url_slug
    } else {
      // Step 2: Create new client_portal_access record (url_slug is auto-generated by trigger)
      console.log('🆕 Creating new client_portal_access record for project:', projectId)
      
      const { data: newAccess, error: createError } = await supabase
        .from('client_portal_access')
        .insert({
          project_id: projectId,
          is_active: true,
          email: clientEmail || null
        })
        .select('url_slug')
        .single()

      if (createError) {
        console.error('❌ Error creating portal access:', createError)
        throw createError
      }

      urlSlug = newAccess.url_slug
      console.log('✅ Created portal access with slug:', urlSlug)
    }

    // Step 3: Build the portal URL (from env or fallback to SITE_URL)
    const siteUrl = Deno.env.get('SITE_URL') || 'https://example.com'
    const portalUrl = `${siteUrl}/client-portal/${urlSlug}`
    console.log('🔗 Portal URL:', portalUrl)

    // Step 4: Send SMS via Twilio
    const twilioAccountSid = Deno.env.get('TWILIO_ACCOUNT_SID')
    const twilioAuthToken = Deno.env.get('TWILIO_AUTH_TOKEN')
    const twilioPhoneNumber = Deno.env.get('TWILIO_PHONE_NUMBER')

    if (!twilioAccountSid || !twilioAuthToken || !twilioPhoneNumber) {
      console.error('❌ Twilio credentials not configured')
      return new Response(
        JSON.stringify({ 
          error: 'SMS service not configured',
          portalUrl,
          urlSlug 
        }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 500 }
      )
    }

    const formattedPhone = formatPhoneToE164(clientPhone)
    const clientDisplayName = clientName || 'there'
    const companyName = Deno.env.get('COMPANY_NAME') || 'Your Team'

    // SMS message - keep it concise for SMS limits
    const smsMessage = `🏠 Welcome to Your Project Portal!

Hi ${clientDisplayName}, your project "${projectName}" is now set up.

Track progress, view updates, and communicate with your team:
${portalUrl}

- ${companyName}`

    console.log('📱 Sending SMS to:', formattedPhone)

    const twilioUrl = `https://api.twilio.com/2010-04-01/Accounts/${twilioAccountSid}/Messages.json`
    
    const smsResponse = await fetch(twilioUrl, {
      method: 'POST',
      headers: {
        'Authorization': `Basic ${btoa(`${twilioAccountSid}:${twilioAuthToken}`)}`,
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: new URLSearchParams({
        To: formattedPhone,
        From: twilioPhoneNumber,
        Body: smsMessage,
      }),
    })

    const smsResult = await smsResponse.json()
    
    if (!smsResponse.ok) {
      console.error('❌ Twilio SMS failed:', smsResult)
      return new Response(
        JSON.stringify({ 
          error: 'Failed to send SMS',
          twilioError: smsResult,
          portalUrl,
          urlSlug
        }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 500 }
      )
    }

    console.log('✅ SMS sent successfully:', smsResult.sid)

    // Step 5: Optionally send welcome email via Resend
    let emailSent = false
    if (clientEmail) {
      const resendApiKey = Deno.env.get('RESEND_API_KEY')
      
      if (resendApiKey) {
        try {
          console.log('📧 Sending welcome email to:', clientEmail)
          
          const emailResponse = await fetch('https://api.resend.com/emails', {
            method: 'POST',
            headers: {
              'Authorization': `Bearer ${resendApiKey}`,
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              from: Deno.env.get('EMAIL_FROM') || `${companyName} <noreply@${siteUrl.replace(/https?:\/\//, '').replace(/^www\./, '')}>`,
              to: clientEmail,
              subject: `🏠 Welcome to Your Project Portal - ${projectName}`,
              html: `
                <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
                  <h1 style="color: #2563eb;">Welcome to Your Project Portal!</h1>
                  <p>Hi ${clientDisplayName},</p>
                  <p>Your roofing project <strong>"${projectName}"</strong> is now set up.</p>
                  <p>You can track progress, view updates, and communicate with your team through your dedicated portal:</p>
                  <p style="margin: 20px 0;">
                    <a href="${portalUrl}" style="background-color: #2563eb; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">
                      Access Your Portal
                    </a>
                  </p>
                  <p>Or copy this link: <a href="${portalUrl}">${portalUrl}</a></p>
                  <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 30px 0;" />
                  <p style="color: #6b7280; font-size: 14px;">
                    - The Roofing Friend Team
                  </p>
                </div>
              `,
            }),
          })

          if (emailResponse.ok) {
            emailSent = true
            console.log('✅ Welcome email sent successfully')
          } else {
            const emailError = await emailResponse.json()
            console.error('❌ Email failed:', emailError)
          }
        } catch (emailErr) {
          console.error('❌ Email error:', emailErr)
        }
      }
    }

    console.log('🎉 Client portal welcome notification complete!')

    return new Response(
      JSON.stringify({ 
        success: true,
        message: 'Client portal welcome notification sent',
        portalUrl,
        urlSlug,
        smsSent: true,
        emailSent
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 200 }
    )

  } catch (error) {
    console.error('❌ Unexpected error in send-client-portal-welcome:', error)
    return new Response(
      JSON.stringify({ error: 'Internal server error', details: error.message }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' }, status: 500 }
    )
  }
})
